name: buurmanenbuurman
favicon: null
layout_spectrum: 0.03135
typography_spectrum: 0.86609
title: 'een Familievoorstelling. Nu in de theaters '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ac0000'
    - '#020102'
    - '#a96157'
    - '#1449e4'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
