name: buurmanenbuurman
favicon: null
layout_spectrum: 0.9738992438651621
typography_spectrum: 0.030687872786074877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00558c'
    - '#f8b332'
    - '#e9591a'
    - '#730000'
  brandStrength: 0.9863163789268583
  lightness: 0.9035598752088845
  saturation: 0.829433485865593
  rhythmicContrast: 0.28008197736926377
purpose: []
